name: Node.js Continuous Integration

on:
  pull_request:
    branches: [ "dev", "main" ]

  workflow_dispatch:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies    
        run: npm ci
      - name: Build TS files
        run: npm run build
        working-directory: ./npm-package
      - name: Start express server
        run: npm start
        working-directory: ./npm-package
      - name: Run backend tests
        run: npm test
        working-directory: ./npm-package
